nxt_robot:
  - type: motor
    name: r_wheel_joint
    port: PORT_A
    desired_frequency: 20.0

  - type: motor
    name: l_wheel_joint
    port: PORT_C
    desired_frequency: 20.0

  - type: touch
    name: touch
    frame_id: r_touch_link
    port: PORT_1
    desired_frequency: 1.0

  - type: ultrasonic
    frame_id: ultrasonic_link
    name: ultrasonic_sensor
    port: PORT_2
    spread_angle: 0.05
    min_range: 0.01
    max_range: 2.5
    desired_frequency: 4.0

  - type: sound
    frame_id: sound_link
    name: sound
    port: PORT_3
    adjusted: 1
    desired_frequency: 4.0

  - type: light
    frame_id: light_link
    name: light
    port: PORT_4
    illuminated: 1
    desired_frequency: 4.0
